{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-4.0.fullname" . }}-spark-rolebinding
  labels:
    {{- include "spark-4.0.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark-4.0.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-4.0.fullname" . }}-spark-role
{{- end }}
