{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName | default "spark-40" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: spark-connect
    chart: spark-4.0
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
