apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-celeborn
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "spark-custom:4.1.0"
  sparkVersion: "4.1.0"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples.jar"
  arguments:
    - "1000"
  sparkConf:
    spark.shuffle.manager: "org.apache.spark.shuffle.celeborn.RssShuffleManager"
    spark.celeborn.master.endpoints: "celeborn-master-0.celeborn-master:9097"
    spark.celeborn.push.replicate.enabled: "true"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/4.1/events"
    spark.hadoop.fs.s3a.endpoint: "minio:9000"
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-41
  executor:
    cores: 1
    instances: 2
    memory: "512m"
  restartPolicy:
    type: Never
