apiVersion: v2
name: spark-3.5
version: 0.1.0
appVersion: "3.5.3"
description: Apache Spark 3.5.3 (Spark Connect + K8s Native)

dependencies:
  - name: spark-base
    version: 0.1.0
    repository: "file://../spark-base"
    condition: spark-base.enabled
