{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-connect-executors
  namespace: {{ .Release.Namespace }}
  labels:
    app: spark-connect
    component: executor
    chart: spark-4.1
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      spark-role: executor
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: {{ .Values.monitoring.podMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout | default "10s" }}
    {{- with .Values.monitoring.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
