{{- if and .Values.airflow.enabled .Values.airflow.fernetKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-standalone.fullname" . }}-airflow-fernet-key
  labels:
    app: airflow
    {{- include "spark-standalone.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: {{ .Values.airflow.fernetKey | quote }}
{{- end }}

