{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-4.1.serviceAccountName" . }}
  labels:
    {{- include "spark-4.1.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-4.1.fullname" . }}-spark-role
  labels:
    {{- include "spark-4.1.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-4.1.fullname" . }}-spark-rolebinding
  labels:
    {{- include "spark-4.1.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark-4.1.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-4.1.fullname" . }}-spark-role
{{- end }}
