{{- if and .Values.sparkMaster.enabled .Values.sparkMaster.ha.enabled .Values.sparkMaster.ha.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-standalone.fullname" . }}-master-recovery
  labels:
    app: spark-master
    {{- include "spark-standalone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.sparkMaster.ha.persistence.storageClass }}
  storageClassName: {{ .Values.sparkMaster.ha.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sparkMaster.ha.persistence.size }}
{{- end }}

