{{- if .Values.sparkWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-standalone.fullname" . }}-worker
  labels:
    app: spark-worker
    {{- include "spark-standalone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sparkWorker.replicas }}
  selector:
    matchLabels:
      app: spark-worker
      {{- include "spark-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: spark-worker
        {{- include "spark-standalone.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spark-standalone.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: spark-worker
        image: "{{ .Values.sparkWorker.image.repository }}:{{ .Values.sparkWorker.image.tag }}"
        imagePullPolicy: {{ .Values.sparkWorker.image.pullPolicy }}
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_HOST
          value: "{{ include "spark-standalone.fullname" . }}-master"
        - name: SPARK_MASTER_PORT
          value: "{{ .Values.sparkMaster.service.ports.spark }}"
        - name: SPARK_WORKER_CORES
          value: "{{ .Values.sparkWorker.cores }}"
        - name: SPARK_WORKER_MEMORY
          value: "{{ .Values.sparkWorker.memory }}"
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: spark-env
              key: S3_ENDPOINT
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        ports:
        - name: worker
          containerPort: {{ .Values.sparkWorker.service.ports.worker }}
        - name: webui
          containerPort: {{ .Values.sparkWorker.service.ports.webui }}
        resources:
          {{- toYaml .Values.sparkWorker.resources | nindent 10 }}
        volumeMounts:
        - name: spark-config
          mountPath: /opt/spark/conf/spark-defaults.conf
          subPath: spark-defaults.conf
        - name: log4j2
          mountPath: /opt/spark/conf/log4j2.properties
          subPath: log4j2.properties
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
          items:
          - key: spark-defaults.conf
            path: spark-defaults.conf
      - name: log4j2
        configMap:
          name: spark-config
          items:
          - key: log4j2.properties
            path: log4j2.properties
{{- end }}
