{{- if .Values.core.postgresql.enabled }}
{{- $chartName := .Chart.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark.core.postgresql.fullname" . }}-credentials
  labels:
    helm.sh/chart: {{ $chartName }}-{{ .Chart.Version }}
    app.kubernetes.io/component: "postgresql"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.core.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.core.postgresql.auth.password | quote }}
{{- end }}
