{{- if and .Values.core.postgresql.enabled (not .Values.core.postgresql.auth.existingSecret) }}
{{- $chartName := .Chart.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark.core.postgresql.fullname" . }}-credentials
  labels:
    helm.sh/chart: {{ $chartName }}-{{ .Chart.Version }}
    app.kubernetes.io/component: "postgresql"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.core.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.core.postgresql.auth.password | quote }}
  {{- if .Values.core.hiveMetastore.enabled }}
  # Hive Metastore credentials
  HIVE_USER: {{ .Values.core.hiveMetastore.postgresql.username | default "hive" | quote }}
  HIVE_PASSWORD: {{ .Values.core.hiveMetastore.postgresql.password | default (randAlphaNum 24) | quote }}
  {{- end }}
{{- end }}
