{{/*
ServiceMonitor for Spark Connect and Spark pods

This ServiceMonitor allows Prometheus to scrape metrics from
Spark ServiceMonitor endpoints created by Spark pods.
*/}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spark.name" . }}-servicemonitor
  namespace: {{ include "spark.namespace" . }}
  labels:
    app: spark
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: spark
      spark-role: driver
  endpoints:
    - port: metrics
      path: /metrics/prometheus
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ include "spark.namespace" . }}
  query: '{__name__="spark_driver_metrics"}'
  interval: 30s
