{{- if .Values.core.hiveMetastore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.core.hiveMetastore.fullname" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: "hive-metastore"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-hive-metastore
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: thrift
      port: {{ .Values.core.hiveMetastore.service.port }}
      targetPort: thrift
{{- end }}
