{{- if and .Values.mlflow.enabled .Values.mlflow.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-standalone.fullname" . }}-postgresql-mlflow-credentials
  labels:
    app: postgresql-mlflow
    {{- include "spark-standalone.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.mlflow.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.mlflow.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.mlflow.postgresql.password | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-standalone.fullname" . }}-postgresql-mlflow-data
  labels:
    app: postgresql-mlflow
    {{- include "spark-standalone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mlflow.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.mlflow.postgresql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mlflow.postgresql.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mlflow.postgresql.host }}
  labels:
    app: postgresql-mlflow
    {{- include "spark-standalone.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-mlflow
      {{- include "spark-standalone.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql-mlflow
        {{- include "spark-standalone.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgresql
        image: "postgres:16-alpine"
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ include "spark-standalone.fullname" . }}-postgresql-mlflow-credentials
        ports:
        - name: postgres
          containerPort: {{ .Values.mlflow.postgresql.port }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        {{- if .Values.mlflow.postgresql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "spark-standalone.fullname" . }}-postgresql-mlflow-data
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mlflow.postgresql.host }}
  labels:
    app: postgresql-mlflow
    {{- include "spark-standalone.labels" . | nindent 4 }}
spec:
  selector:
    app: postgresql-mlflow
    {{- include "spark-standalone.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: {{ .Values.mlflow.postgresql.port }}
    targetPort: postgres
{{- end }}
