apiVersion: v1
kind: Service
metadata:
  name: {{ include "celeborn.fullname" . }}-master
  labels:
    {{- include "celeborn.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: {{ .Values.master.service.port }}
      targetPort: rpc
  selector:
    app: celeborn-master
    {{- include "celeborn.selectorLabels" . | nindent 4 }}
