apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "celeborn.fullname" . }}-master
  labels:
    {{- include "celeborn.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "celeborn.fullname" . }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: celeborn-master
      {{- include "celeborn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: celeborn-master
        {{- include "celeborn.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          command:
            - /opt/celeborn/sbin/start-master.sh
          ports:
            - containerPort: {{ .Values.master.service.port }}
              name: rpc
          volumeMounts:
            - name: config
              mountPath: /opt/celeborn/conf
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "celeborn.fullname" . }}-config
