apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
  namespace: dataops
data:
  SPARK_MASTER_URL: "spark://spark-master:7077"
  SPARK_HOME: "/opt/spark"
  S3_ENDPOINT_URL: "http://minio:9000"
  AWS_S3_SIGNATURE_VERSION: "s3v4"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  PYSPARK_PYTHON: "python3"
  PYSPARK_DRIVER_PYTHON: "python3"
  JUPYTERHUB_NAMESPACE: "dataops"
  JUPYTERHUB_IMAGE: "jupyterhub-spark:latest"
  JUPYTERHUB_SERVICE_ACCOUNT: "jupyterhub"

